version: "3"
services:
    client:
        build:
            dockerfile: ./docker/Dockerfile.client
            context: .
        user: root
        volumes:
            - CruizinVolume:/app/opt
        depends_on:
            - "db"
    server:
        build:
            dockerfile: ./docker/Dockerfile.server
            context: .
        ports:
            - "3000:3000"
        env_file:
            - ./docker/env.list
        user: root
        volumes:
            - CruizinVolume:/app/opt
        depends_on:
            - "client"
    db:
        build:
            dockerfile: ./docker/Dockerfile.database
            context: .
        user: root
        volumes:
            - CruizinVolume:/app/opt
volumes:
    CruizinVolume: