FROM golang:buster

WORKDIR '/app'

COPY ./go.mod .
COPY ./go.sum .
COPY ./server/ ./server
COPY ./prod.env .

RUN cd server && go build -o cruizinserver

CMD ["mv", "./server/cruizinserver", "./opt"]
CMD ["./opt/cruizinserver"]