FROM golang:buster

WORKDIR '/app'

COPY ./go.mod .
COPY ./go.sum .
COPY ./server/ ./server

RUN cd server && go build -o ../cruizinserver && cd ../
RUN rm ./go.*
RUN rm -rf server

CMD ["mv", "./cruizinserver", "./opt"]
CMD ["./opt/cruizinserver"]
