version: "3"
services:
    web:
        build:
            context: ../
            dockerfile: docker/Dockerfile.client
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - ../web:/app
    tests:
        build:
            context: ../
            dockerfile: docker/Dockerfile.client
        volumes:
            - /app/node_modules
            - ../web:/app
        command: ["npm", "run", "test"]